busy = false;
task = "none";
target_id = -2;
target_x = 0;
target_y = 0;
work_per_second = 1;
walk_speed = 64;
en_route = false;
work_to_complete = 1;
home = 0;
home_x = 0;
home_y = 0;
slot = 0;
pause = false;
hunger = 0; //days without eating
tried_to_eat = false; //have i tried to eat today, reset everyday
daily_done = false;
path = path_add();
map = global.road_network;