busy = false;
has_task = false;
task = "none";
end_task = false;
target_id = -2;
target_x = 0;
target_y = 0;
work_per_second = 1;
walk_speed = 128;
speed_mod = 3; ///
en_route = false;
transport_item = "none";
transport_value = 0;
slot = 0;
picked_up = false;
transport_to_site_id = -2;
value_needed = 0;
item_needed = "none";
pause = false;
repetitions_remaining = 0;
hunger = 0; //days without eating
tried_to_eat = false; //have i tried to eat today, reset everyday
daily_done = false;
selected = false;
manual_input = false;
path = path_add();
map = global.workers_map;
path_success = false;

sprite_index = choose(spr_builder, spr_builder_blonde, spr_builder_black, spr_builder_moustache, spr_builder_moustache_blonde, spr_builder_moustache_black, spr_builder_beard, spr_builder_beard_blonde, spr_builder_beard_black, spr_builder_wizard, spr_builder_wizard_blonde, spr_builder_wizard_black);